# Data
data_name: 'AlibabaLoan'
data_dir: './data/'
train_ratio: 0.8
test_ratio: 0.27
save_dir: './pytorch_models/'

# Model
model: 'GCN'
multi_relation: 'GNN'


# Model architecture
emb_size:
  - 32
  - 64

thres:
  - 0.4
  - 0.5

rho: 0.4

seed: 42

# # Run multiple times with different random seeds
# seed:
#     - 42
#     - 72
    # - 448
    # - 854
    # - 29493
    # - 88867


# hyper-parameters
optimizer: 'adam'
lr: #0.005
  - 0.001
  - 0.002
  - 0.005
weight_decay: #0.0001
  - 0.0001
  - 0.0005
batch_size:
  - 256
  - 1024
num_epochs:
  - 51
  - 100
valid_epochs:
  - 10
alpha: 2


# Device
no_cuda: True
cuda_id: '2'
