# Data
# comp dataset， 调整用的，效果还没调
data_name: 'comp'
data_dir: './data/'
train_ratio: 0.8
test_ratio: 0.27
save_dir: './pytorch_models/'

# Model
#model: 'SAGE'
#model: 'GCN'
model: 'PCGNN'
multi_relation: 'GNN'


# Model architecture
emb_size: 64

thres: 0.4

rho: 0.8
#rho:
#   - 0.2
#   - 0.4
#   - 0.6
#   - 0.8

seed: 72

# # Run multiple times with different random seeds
# seed:
#     - 42
#     - 448
#     - 854
#     - 29493
#     - 88867


# hyper-parameters
optimizer: 'adam'
lr: 0.005
weight_decay: 0.0001
batch_size: 256
num_epochs: 500
valid_epochs: 5
alpha: 2


# Device
no_cuda: True
cuda_id: '2'
